# Site settings
name: Less Or More
email: wangyn65@gmail.com
author: Freud Kang
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/imwyn
baseurl: 'https://imwyn.github.io/no9730416.github.io/'
description: Actually, less is more!
meta_description: no930416;个人博客;good good study, day day up
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: imwyn

# Build settings
markdown: kramdown
